### ISSUE TITLE
TestFlight Beta isn‘t accepting any new testers

### ISSUE THREAD

**Issue by fbernutz** [criticalmaps/criticalmaps-ios#167]
Hi, I would love to join the beta, but the link on the readme says that the beta isn‘t accepting any new testers. This is kind of disappointing. If there are enough testers already, maybe you should remove the link in the readme or higher the number of maximum testers ✌️

**Comment by mltbnz** [comment]
It is because currently there is no TestFlight build. The last one ran out after 90 days. We wanted to have a pipeline where changed in develop will trigger a new TestFlight build but there are some implications with the certificate and program that is used to distribute the app. 
I agree though that it is disappointing 😕 But help is on the way 👩‍💻👨‍💻

**Comment by fbernutz** [comment]
Ah I see, thanks for the clarification! 
Will there be new beta versions in the next time? If not, you still have the option to remove the link and add it again if the automation process is implemented.
But feel free to close this issue, if there’s nothing to do right now.

**Comment by mltbnz** [comment]
I hope we have a new beta in the next couple of days. Until then it is actually a good idea to temporally remove the link from the readme. But I'll wait a little longer and if beta == true I will give you a note here. Otherwise I'll remove the link in the readme and close this issue

**Comment by mltbnz** [comment]
Could you try again to subscribe? Should work now

**Comment by fbernutz** [comment]
Yes, it worked! 😊 Thanks for the notification

**Comment by fbernutz** [comment]
Yes, it worked! 😊 Thanks for the notification
