### ISSUE TITLE
Display Error message if we can't update the Map

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#268]
<img width="335" alt="Bildschirmfoto 2020-03-10 um 14 01 09" src="https://user-images.githubusercontent.com/7677738/76314704-9aa1b100-62d7-11ea-9749-fce72cfb000e.png">

We want to display an Error message if we are unable to update the data. Parts of the feature like UI are already implemented but the connection between UI and the RequestManager is missing.

Might be useful to implement #245 first

**Comment by mltbnz** [comment]
Think so too. I’ll see if I can work on it in the next weeks. For showing errors in the Mai the info presenter needs a queue or something I guess since atm the first error would dismiss the next event Info view 😄 
I think one solution could be to present it under the event info view and then give it a time to dismiss itself after 4 seconds for example. These things are always little tricky with all the cases

**Comment by mltbnz** [comment]
Since I stashed the code I quickly hacked this together and I think there needs to be some logic in place on how often we display the errors. With every fetch?

![errordemo](https://user-images.githubusercontent.com/14075359/76501660-f76daa80-6442-11ea-80b6-9b3cb9884c02.gif)

**Comment by lennet** [comment]
In my opinion the Error message should only automatically disappear if we successfully updated the data

**Comment by mltbnz** [comment]
Maybe then it could change into a success message and then disappear

**Comment by lennet** [comment]
Cc @zutrinken
