### ISSUE TITLE
Does The Upcoming Events/Notifications Feature Work?

### ISSUE THREAD

**Issue by pqhf5kd** [criticalmaps/criticalmaps-ios#434]
I recently installed Critical Maps on iOS and created an event on criticalmass.in for my local ride.
Should I be able to see the event in the app?

**Comment by mltbnz** [comment]
It should appear. The API sometimes responds with only `cancelled` rides when rides shouldn't take place because of high corona incidence numbers. But the app atm simply does not show any rides then and will not show a UI element. You could check the console log though which would give you a hint why the event does not take place.

The `NextRidesRequest` will query the API with a URL like:
https://criticalmass.in/api/ride?centerLongitude=13.417989192905827&centerLatitude=52.52075691889381&radius=10&year=2022&month=2

You could replace the `centerLongitude=13.417989192905827&centerLatitude=52.52075691889381` part with your coordinates and check if your event appears in the response

**Comment by pqhf5kd** [comment]
https://criticalmass.in/api/ride?centerLongitude=21.259781&centerLatitude=48.717110&radius=10&year=2022&month=2

The API appears to show the event when I use my location.

Will V4 of the app have a page showing all upcoming events in the area?

**Comment by mltbnz** [comment]
Atm no. But I was thinking about that feature and if people would bee using it. I guess it could be a simple list. Just need to figure out where to put it 🤔

**Comment by mltbnz** [comment]
@pqhf5kd I have added the feature to show all events in an area in #442
