### ISSUE TITLE
Active / Inactive Location Icon

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#44]
When the map got moved and isn't following my own position the location icon should be outlined as in apple or google maps.

![img_4265](https://user-images.githubusercontent.com/888679/52232907-07b96a80-28be-11e9-9bd7-db12f2be6f1b.PNG)
![img_4266](https://user-images.githubusercontent.com/888679/52232908-07b96a80-28be-11e9-88e8-170986aaffc4.PNG)

**Comment by lennet** [comment]
We should use 
on/mapkit/mkusertrackingbutto
https://developer.apple.com/documentation/mapkit/mkusertrackingbutton which provides the maps behavior + UI for free

**Comment by lennet** [comment]
It looks like the MKUserTrackingButton isn't working for us because its inverting the colors on selection instead of filling the icon and there is no api to change that behavior. The line width of the arrow icon seems to be thinner than the line width of the other icons 

![2019-02-16 14-42-12 2019-02-16 14_43_03](https://user-images.githubusercontent.com/7677738/52900697-2f330000-31f9-11e9-8a3b-3a826318fabe.gif)
