### ISSUE TITLE
Message notification bubble

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#67]
show a notification bubble for new unread messages

<img src="https://user-images.githubusercontent.com/888679/55789628-fefe3400-5aba-11e9-9c64-558bd40cd595.png" alt="screenshot" width="375" height="88" />

**Comment by lennet** [comment]
I would love to have that feature! 
Is there a way to disable or enable it as some users might be annoyed by seeing the bubble if they are not interested in using the chat?

We could probably use the systems push notifications API for that especially because once we have the logic for the bubble, push notifications wouldn't be much work while the app is running in the background. 

For the implementation, we would require some sort of persistent cache which would replace the current used MemoryDataStore to know which messages are unread after an app restart

**Comment by zutrinken** [comment]
I see it this way:

Since messages are rarely used for now (not sure if they're watched a lot) I'd go for no turning off option until we negative feedback. I'd like to see it used more often first.

Push notifications are related but a different story imo. Nonetheless definitely something we should add. And push notifications can be turned off by system anyway.

So without push notifications the bubble shouldn't be to annoying.
